### ISSUE TITLE
github workflow (Generate Docker Metadata) is user specific

### ISSUE THREAD

**Issue by gedw99** [BrenekH/docker-hub-ghcr-test#2]
thanks for this project. It works well for me.

Any chance this can be a variable ? 
https://github.com/BrenekH/docker-hub-ghcr-test/blob/master/.github/workflows/docker.yaml#L68

**Comment by BrenekH** [comment]
What sort of variable did you have in mind?

There are a couple of options while keeping to the original goal of this project, which is first and foremost, just a testing playground for me to try out GitHub Actions with Docker Hub and the GitHub Container Registry without affecting any "real" project I may want to use the workflow for.

Using the secrets context:

```yaml
...
        with:
          images: |
            ${{ secrets.CONTAINER_TAG }}
            ghcr.io/${{ secrets.CONTAINER_TAG }}
...
```

Using an environment variable from a previous step:

```yaml
...
      - name: Set CONTAINER_TAG github env var
        run: echo "CONTAINER_TAG=brenekh/docker-hub-ghcr-test" >> $GITHUB_ENV

      - name: Generate Docker Metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ env.CONTAINER_TAG }}
            ghcr.io/${{ env.CONTAINER_TAG }}
...
```

Using an environment variable set in the `env` block (I'm not sure that this actually works, but I think it should):

```yaml
...
      - name: Generate Docker Metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        env:
          CONTAINER_TAG: brenekh/docker-hub-ghcr-test
        with:
          images: |
            ${{ env.CONTAINER_TAG }}
            ghcr.io/${{ env.CONTAINER_TAG }}
...
```
